# Generated by Django 3.0.8 on 2021-04-18 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(default='', max_length=100)),
                ('subheading', models.CharField(default='', max_length=100)),
                ('content', models.TextField()),
                ('imagee', models.ImageField(default='', upload_to='images')),
            ],
        ),
    ]
