# Generated by Django 2.2.13 on 2021-04-29 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0005_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='data',
            name='link',
            field=models.URLField(default=''),
        ),
    ]
